"""create session model

Revision ID: 0d18e70b7a1a
Revises: 82312431bf88
Create Date: 2023-06-02 11:01:59.607576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d18e70b7a1a'
down_revision = '82312431bf88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tgsession',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_string', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_string')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tgsession')
    # ### end Alembic commands ###
