"""change post an mediafile models

Revision ID: 14a236caed8a
Revises: 22551413e4ed
Create Date: 2023-05-26 19:32:39.644698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14a236caed8a'
down_revision = '22551413e4ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
