"""remove uselist

Revision ID: 22551413e4ed
Revises: 3cd03b611e39
Create Date: 2023-05-26 19:13:02.127953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22551413e4ed'
down_revision = '3cd03b611e39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
