"""change post model

Revision ID: 23cac42e08dc
Revises: 0019f63a3088
Create Date: 2023-05-29 14:09:14.268248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23cac42e08dc'
down_revision = '0019f63a3088'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
