"""add urltype for media

Revision ID: 3cd03b611e39
Revises: 1455980480e9
Create Date: 2023-05-23 15:59:51.092760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cd03b611e39'
down_revision = '1455980480e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
