"""change user model

Revision ID: 82312431bf88
Revises: 23cac42e08dc
Create Date: 2023-05-31 13:57:44.461807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82312431bf88'
down_revision = '23cac42e08dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
