"""add users

Revision ID: 95281c881af0
Revises: bbd6e811120c
Create Date: 2023-05-18 20:27:57.668733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95281c881af0'
down_revision = 'bbd6e811120c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
