"""add optional mediafiles

Revision ID: cf9dbee89d33
Revises: fd3dcafd29b3
Create Date: 2023-05-23 11:12:03.592326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf9dbee89d33'
down_revision = 'fd3dcafd29b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
