"""add target to post

Revision ID: fa5c0bd92f57
Revises: 14a236caed8a
Create Date: 2023-05-26 23:01:42.088767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa5c0bd92f57'
down_revision = '14a236caed8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('target_channel_id',
                                    sa.Integer(), nullable=True))
    op.alter_column('post', 'is_verified',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.create_foreign_key(None, 'post', 'target',
                          ['target_channel_id'], ['id'])
    op.alter_column('target', 'active',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.alter_column('target', 'forwarding',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('target', 'forwarding',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.alter_column('target', 'active',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.alter_column('post', 'is_verified',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.drop_column('post', 'target_channel_id')
    # ### end Alembic commands ###
