"""add lazy

Revision ID: fd3dcafd29b3
Revises: 95281c881af0
Create Date: 2023-05-20 10:46:32.097621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd3dcafd29b3'
down_revision = '95281c881af0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
